### ISSUE TITLE
Issue with the main_installer.sh saying Integration Bridge is not Present.

### ISSUE THREAD

**Issue by kylebaker** [tigerlinux/openstack-queens-installer-ubuntu1604lts#1]
In the /DOCS/NOTES.txt I have run the following commands:

ovs-vsctl add-br br-int
ovs-vsctl add-br br-eth2
ovs-vsctl add-port br-eth2 ens38

When I 'sudo ovs-vsctl show', I see there are two bridges. 

When I run the 'main_installer.sh' and it gets to line 126 of 'requeriments.sh', my $internalbridgepresent variable is a '2' when it wants a '1' to validate. But again, the instructions from the NOTES.txt tell me to add two bridges. Am I doing something wrong that I am not seeing? 

Thanks

**Comment by tigerlinux** [comment]
Hi there,

Sorry for the delay but I've been too busy lately. It seems that you have two br-int's (weird situation). Sadly I could not reproduce the problem you are facing.
